[[positions]]
id = "EKDK_FMP"
prefixes = ["EKDK"]
frequency = "131.040"
facility_type = "FMP"

[[positions]]
id = "EKDK_A_CTR"
prefixes = ["EKDK"]
frequency = "135.290"
facility_type = "CTR"

[[positions]]
id = "EKDK_B_CTR"
prefixes = ["EKDK"]
frequency = "119.555"
facility_type = "CTR"

[[positions]]
id = "EKDK_CTR"
prefixes = ["EKDK"]
frequency = "136.555"
facility_type = "CTR"

[[positions]]
id = "EKDK_C_CTR"
prefixes = ["EKDK"]
frequency = "128.215"
facility_type = "CTR"

[[positions]]
id = "EKDK_D_CTR"
prefixes = ["EKDK"]
frequency = "133.155"
facility_type = "CTR"

[[positions]]
id = "EKDK_E_CTR"
prefixes = ["EKDK"]
frequency = "123.730"
facility_type = "CTR"

[[positions]]
id = "EKDK_I_CTR"
prefixes = ["EKDK"]
frequency = "121.380"
facility_type = "CTR"

[[positions]]
id = "EKDK_L_CTR"
prefixes = ["EKDK"]
frequency = "124.555"
facility_type = "CTR"

[[positions]]
id = "EKDK_M_CTR"
prefixes = ["EKDK"]
frequency = "130.990"
facility_type = "CTR"

[[positions]]
id = "EKDK_N_CTR"
prefixes = ["EKDK"]
frequency = "134.680"
facility_type = "CTR"

[[positions]]
id = "EKDK_UA_CTR"
prefixes = ["EKDK"]
frequency = "136.485"
facility_type = "CTR"

[[positions]]
id = "EKDK_UC_CTR"
prefixes = ["EKDK"]
frequency = "127.865"
facility_type = "CTR"

[[positions]]
id = "EKDK_UN_CTR"
prefixes = ["EKDK"]
frequency = "136.555"
facility_type = "CTR"

[[positions]]
id = "EKDK_UV_CTR"
prefixes = ["EKDK"]
frequency = "126.055"
facility_type = "CTR"

[[positions]]
id = "EKDK_V_CTR"
prefixes = ["EKDK"]
frequency = "135.565"
facility_type = "CTR"

[[positions]]
id = "EKCH_K_DEP"
prefixes = ["EKCH"]
frequency = "124.980"
facility_type = "DEP"

[[positions]]
id = "EKCH_R_DEP"
prefixes = ["EKCH"]
frequency = "120.255"
facility_type = "DEP"

[[positions]]
id = "EKAH_APP"
prefixes = ["EKAH"]
frequency = "119.280"
facility_type = "APP"

[[positions]]
id = "EKBI_APP"
prefixes = ["EKBI"]
frequency = "127.580"
facility_type = "APP"

[[positions]]
id = "EKBI_F_APP"
prefixes = ["EKBI"]
frequency = "119.255"
facility_type = "APP"

[[positions]]
id = "EKBI_M_APP"
prefixes = ["EKBI"]
frequency = "130.980"
facility_type = "APP"

[[positions]]
id = "EKCH_F_APP"
prefixes = ["EKCH"]
frequency = "120.205"
facility_type = "APP"

[[positions]]
id = "EKCH_M_APP"
prefixes = ["EKCH"]
frequency = "130.985"
facility_type = "APP"

[[positions]]
id = "EKCH_O_APP"
prefixes = ["EKCH"]
frequency = "118.455"
facility_type = "APP"

[[positions]]
id = "EKCH_P_APP"
prefixes = ["EKCH"]
frequency = "131.405"
facility_type = "APP"

[[positions]]
id = "EKCH_W_APP"
prefixes = ["EKCH"]
frequency = "119.805"
facility_type = "APP"

[[positions]]
id = "EKKA_APP"
prefixes = ["EKKA"]
frequency = "120.430"
facility_type = "APP"

[[positions]]
id = "EKRK_APP"
prefixes = ["EKRK"]
frequency = "125.530"
facility_type = "APP"

[[positions]]
id = "EKSP_APP"
prefixes = ["EKSP"]
frequency = "124.105"
facility_type = "APP"

[[positions]]
id = "EKYT_APP"
prefixes = ["EKYT"]
frequency = "123.980"
facility_type = "APP"

[[positions]]
id = "EKYT_F_APP"
prefixes = ["EKYT"]
frequency = "120.705"
facility_type = "APP"

[[positions]]
id = "EKAH_TWR"
prefixes = ["EKAH"]
frequency = "118.530"
facility_type = "TWR"

[[positions]]
id = "EKBI_TWR"
prefixes = ["EKBI"]
frequency = "119.005"
facility_type = "TWR"

[[positions]]
id = "EKCH_A_TWR"
prefixes = ["EKCH"]
frequency = "118.105"
facility_type = "TWR"

[[positions]]
id = "EKCH_C_TWR"
prefixes = ["EKCH"]
frequency = "118.580"
facility_type = "TWR"

[[positions]]
id = "EKCH_D_TWR"
prefixes = ["EKCH"]
frequency = "119.355"
facility_type = "TWR"

[[positions]]
id = "EKEB_I_TWR"
prefixes = ["EKEB"]
frequency = "120.155"
facility_type = "TWR"

[[positions]]
id = "EKKA_TWR"
prefixes = ["EKKA"]
frequency = "119.580"
facility_type = "TWR"

[[positions]]
id = "EKOD_I_TWR"
prefixes = ["EKOD"]
frequency = "119.530"
facility_type = "TWR"

[[positions]]
id = "EKRK_TWR"
prefixes = ["EKRK"]
frequency = "118.905"
facility_type = "TWR"

[[positions]]
id = "EKRN_P_TWR"
prefixes = ["EKRN"]
frequency = "118.330"
facility_type = "TWR"

[[positions]]
id = "EKSB_I_TWR"
prefixes = ["EKSB"]
frequency = "126.405"
facility_type = "TWR"

[[positions]]
id = "EKSP_TWR"
prefixes = ["EKSP"]
frequency = "118.280"
facility_type = "TWR"

[[positions]]
id = "EKVJ_I_TWR"
prefixes = ["EKVJ"]
frequency = "121.405"
facility_type = "TWR"

[[positions]]
id = "EKYT_TWR"
prefixes = ["EKYT"]
frequency = "118.305"
facility_type = "TWR"

[[positions]]
id = "EKCH_A_GND"
prefixes = ["EKCH"]
frequency = "121.630"
facility_type = "GND"

[[positions]]
id = "EKCH_B_GND"
prefixes = ["EKCH"]
frequency = "121.905"
facility_type = "GND"

[[positions]]
id = "EKCH_C_GND"
prefixes = ["EKCH"]
frequency = "121.730"
facility_type = "GND"

[[positions]]
id = "EKCH_DEL"
prefixes = ["EKCH"]
frequency = "119.905"
facility_type = "DEL"
