[[stations]]
id = "LOVV_FMP"
controlled_by = ["LOVV_FMP"]

[[stations]]
id = "LOVV_B1"
controlled_by = [
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_W_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_BU_CTR",
  "LOVV_WU_CTR",
  "LOVV_NU_CTR",
  "LOVV_U_CTR",
]

[[stations]]
id = "LOVV_B2"
parent_id = "LOVV_B3"

[[stations]]
id = "LOVV_B3"
parent_id = "LOVV_B4"

[[stations]]
id = "LOVV_B4"
parent_id = "LOVV_B5"

[[stations]]
id = "LOVV_B5"
parent_id = "LOVV_B6"

[[stations]]
id = "LOVV_B6"
parent_id = "LOVV_B7"

[[stations]]
id = "LOVV_B7"
controlled_by = [
  "LOVV_BU_CTR",
  "LOVV_WU_CTR",
  "LOVV_NU_CTR",
  "LOVV_U_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_W_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
]

[[stations]]
id = "LOVV_E1"
controlled_by = [
  "LOVV_E_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_EU_CTR",
  "LOVV_NU_CTR",
  "LOVV_U_CTR",
]

[[stations]]
id = "LOVV_E2"
parent_id = "LOVV_E3"

[[stations]]
id = "LOVV_E3"
parent_id = "LOVV_E4"

[[stations]]
id = "LOVV_E4"
parent_id = "LOVV_E5"

[[stations]]
id = "LOVV_E5"
parent_id = "LOVV_E6"

[[stations]]
id = "LOVV_E6"
parent_id = "LOVV_E7"

[[stations]]
id = "LOVV_E7"
controlled_by = [
  "LOVV_EU_CTR",
  "LOVV_NU_CTR",
  "LOVV_U_CTR",
  "LOVV_E_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
]

[[stations]]
id = "LOVV_N1"
controlled_by = [
  "LOVV_F_CTR",
  "LOVV_N_CTR",
  "LOVV_E_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_NU_CTR",
  "LOVV_EU_CTR",
  "LOVV_U_CTR",
]

[[stations]]
id = "LOVV_N2"
parent_id = "LOVV_N3"

[[stations]]
id = "LOVV_N3"
parent_id = "LOVV_N4"

[[stations]]
id = "LOVV_N4"
parent_id = "LOVV_N5"

[[stations]]
id = "LOVV_N5"
parent_id = "LOVV_N6"

[[stations]]
id = "LOVV_N6"
parent_id = "LOVV_N7"

[[stations]]
id = "LOVV_N7"
controlled_by = [
  "LOVV_NU_CTR",
  "LOVV_EU_CTR",
  "LOVV_U_CTR",
  "LOVV_N_CTR",
  "LOVV_E_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
]

[[stations]]
id = "LOVV_S1"
controlled_by = [
  "LOVV_S_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_E_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_SU_CTR",
  "LOVV_BU_CTR",
  "LOVV_EU_CTR",
  "LOVV_U_CTR",
]

[[stations]]
id = "LOVV_S2"
parent_id = "LOVV_S3"

[[stations]]
id = "LOVV_S3"
parent_id = "LOVV_S4"

[[stations]]
id = "LOVV_S4"
parent_id = "LOVV_S5"

[[stations]]
id = "LOVV_S5"
parent_id = "LOVV_S6"

[[stations]]
id = "LOVV_S6"
parent_id = "LOVV_S7"

[[stations]]
id = "LOVV_S7"
controlled_by = [
  "LOVV_SU_CTR",
  "LOVV_BU_CTR",
  "LOVV_EU_CTR",
  "LOVV_U_CTR",
  "LOVV_S_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_E_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
]

[[stations]]
id = "LOVV_W1"
controlled_by = [
  "LOVV_W_CTR",
  "LOVV_S_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_WU_CTR",
  "LOVV_SU_CTR",
  "LOVV_BU_CTR",
  "LOVV_U_CTR",
]

[[stations]]
id = "LOVV_W2"
parent_id = "LOVV_W3"

[[stations]]
id = "LOVV_W3"
parent_id = "LOVV_W4"

[[stations]]
id = "LOVV_W4"
parent_id = "LOVV_W5"

[[stations]]
id = "LOVV_W5"
parent_id = "LOVV_W6"

[[stations]]
id = "LOVV_W6"
parent_id = "LOVV_W7"

[[stations]]
id = "LOVV_W7"
controlled_by = [
  "LOVV_WU_CTR",
  "LOVV_SU_CTR",
  "LOVV_BU_CTR",
  "LOVV_U_CTR",
  "LOVV_W_CTR",
  "LOVV_S_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
]

[[stations]]
id = "LOVV_I_CTR"
controlled_by = ["LOVV_I_CTR"]

[[stations]]
id = "LOVV_M_CTR"
controlled_by = ["LOVV_M_CTR"]

[[stations]]
id = "LOWG_APP"
controlled_by = [
  "LOWG_APP",
  "LOVV_S_APP",
  "LOVV_L_CTR",
  "LOVV_S_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_E_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_SU_CTR",
  "LOVV_BU_CTR",
  "LOVV_EU_CTR",
]

[[stations]]
id = "LOWG_TWR"
parent_id = "LOWG_APP"
controlled_by = ["LOWG_TWR"]

[[stations]]
id = "LOWI_TWR"
parent_id = "LOWI_APP"
controlled_by = ["LOWI_TWR"]

[[stations]]
id = "LOWI_E_APP"
parent_id = "LOWI_APP"
controlled_by = ["LOWI_E_APP", "LOWI_APP", "LOWI_S_APP"]

[[stations]]
id = "LOWI_S_APP"
parent_id = "LOWI_APP"
controlled_by = ["LOWI_S_APP", "LOWI_APP", "LOWI_E_APP"]

[[stations]]
id = "LOWI_F_APP"
parent_id = "LOWI_APP"
controlled_by = ["LOWI_F_APP", "LOWI_E_APP", "LOWI_S_APP"]

[[stations]]
id = "LOWI_APP"
controlled_by = [
  "LOWI_APP",
  "LOWI_E_APP",
  "LOWI_S_APP",
  "LOVV_L_CTR",
  "LOVV_W_CTR",
  "LOVV_S_CTR",
  "LOVV_B_CTR",
  "LOVV_CTR",
  "LOVV_WU_CTR",
  "LOVV_SU_CTR",
  "LOVV_BU_CTR",
]

[[stations]]
id = "LOWK_APP"
controlled_by = [
  "LOWK_APP",
  "LOVV_S_APP",
  "LOVV_L_CTR",
  "LOVV_W_CTR",
  "LOVV_S_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_WU_CTR",
  "LOVV_SU_CTR",
  "LOVV_BU_CTR",
]

[[stations]]
id = "LOWK_TWR"
parent_id = "LOWK_APP"
controlled_by = ["LOWK_TWR"]

[[stations]]
id = "LOWL_APP"
controlled_by = [
  "LOWL_APP",
  "LOVV_N_APP",
  "LOVV_L_CTR",
  "LOVV_N_CTR",
  "LOVV_E_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_NU_CTR",
  "LOVV_EU_CTR",
]

[[stations]]
id = "LOWL_TWR"
parent_id = "LOWL_APP"
controlled_by = ["LOWL_TWR"]

[[stations]]
id = "LOWS_APP"
controlled_by = [
  "LOWS_APP",
  "LOVV_N_APP",
  "LOVV_L_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_W_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_BU_CTR",
  "LOVV_WU_CTR",
  "LOVV_NU_CTR",
]

[[stations]]
id = "LOWS_TWR"
parent_id = "LOWS_APP"
controlled_by = ["LOWS_TWR"]

[[stations]]
id = "LOWW_TWR"
parent_id = "LOWW_APP"
controlled_by = ["LOWW_TWR", "LOWW_E_TWR"]

[[stations]]
id = "LOWW_E_TWR"
parent_id = "LOWW_APP"
controlled_by = ["LOWW_E_TWR", "LOWW_TWR"]

[[stations]]
id = "LOWW_APP"
controlled_by = [
  "LOWW_APP",
  "LOWW_P_APP",
  "LOWW_N_APP",
  "LOWW_M_APP",
  "LOVV_L_CTR",
  "LOVV_E_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_EU_CTR",
  "LOVV_NU_CTR",
]

[[stations]]
id = "LOWW_M_APP"
parent_id = "LOWW_APP"
controlled_by = ["LOWW_M_APP", "LOWW_P_APP", "LOWW_N_APP", "LOWW_APP"]

[[stations]]
id = "LOWW_N_APP"
parent_id = "LOWW_APP"
controlled_by = ["LOWW_N_APP", "LOWW_M_APP", "LOWW_APP", "LOWW_P_APP"]

[[stations]]
id = "LOWW_P_APP"
parent_id = "LOWW_APP"
controlled_by = ["LOWW_P_APP", "LOWW_M_APP", "LOWW_APP", "LOWW_N_APP"]

[[stations]]
id = "LOWW_F_APP"
controlled_by = ["LOWW_F_APP", "LOWW_D_APP"]

[[stations]]
id = "LOWW_D_APP"
controlled_by = ["LOWW_D_APP", "LOWW_F_APP"]

[[stations]]
id = "LOWW_I_APP"
controlled_by = ["LOWW_I_APP", "LOVV_I_CTR"]

[[stations]]
id = "LOXA_TWR"
controlled_by = [
  "LOXA_TWR",
  "LOVV_M_CTR",
  "LOWW_N_APP",
  "LOWW_M_APP",
  "LOWW_APP",
  "LOWW_P_APP",
  "LOVV_L_CTR",
  "LOVV_E_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_EU_CTR",
  "LOVV_NU_CTR",
]

[[stations]]
id = "LOXN_TWR"
controlled_by = [
  "LOXN_TWR",
  "LOVV_M_CTR",
  "LOWW_N_APP",
  "LOWW_M_APP",
  "LOWW_APP",
  "LOWW_P_APP",
  "LOVV_L_CTR",
  "LOVV_E_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_EU_CTR",
  "LOVV_NU_CTR",
]

[[stations]]
id = "LOXT_APP"
controlled_by = [
  "LOXT_APP",
  "LOVV_M_CTR",
  "LOWW_N_APP",
  "LOWW_M_APP",
  "LOWW_APP",
  "LOWW_P_APP",
  "LOVV_L_CTR",
  "LOVV_E_CTR",
  "LOVV_N_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_EU_CTR",
  "LOVV_NU_CTR",
]

[[stations]]
id = "LOXT_P_APP"
parent_id = "LOXT_APP"
controlled_by = ["LOXT_P_APP"]

[[stations]]
id = "LOXT_TWR"
parent_id = "LOXT_APP"
controlled_by = ["LOXT_TWR"]

[[stations]]
id = "LOXZ_APP"
controlled_by = [
  "LOXZ_APP",
  "LOVV_M_CTR",
  "LOWG_APP",
  "LOWK_APP",
  "LOVV_S_APP",
  "LOVV_L_CTR",
  "LOVV_S_CTR",
  "LOVV_W_CTR",
  "LOVV_B_CTR",
  "LOVV_BC_CTR",
  "LOVV_E_CTR",
  "LOVV_CTR",
  "LOVV_C_CTR",
  "LOVV_SU_CTR",
  "LOVV_WU_CTR",
  "LOVV_BU_CTR",
  "LOVV_EU_CTR",
]

[[stations]]
id = "LOXZ_P_APP"
parent_id = "LOXZ_APP"
controlled_by = ["LOXZ_P_APP"]

[[stations]]
id = "LOXZ_TWR"
parent_id = "LOXZ_APP"
controlled_by = ["LOXZ_TWR"]

[[stations]]
id = "LOWW_I_GND"
parent_id = "LOWW_GND"
controlled_by = ["LOWW_I_GND"]

[[stations]]
id = "LOWW_W_GND"
parent_id = "LOWW_GND"
controlled_by = ["LOWW_W_GND", "LOWW_GND", "LOWW_TWR", "LOWW_E_TWR"]

[[stations]]
id = "LOWW_GND"
parent_id = "LOWW_TWR"
controlled_by = ["LOWW_GND", "LOWW_W_GND", "LOWW_E_TWR", "LOWW_TWR"]

[[stations]]
id = "LOWI_DEL"
parent_id = "LOWI_TWR"
controlled_by = ["LOWI_DEL"]

[[stations]]
id = "LOWS_DEL"
parent_id = "LOWS_TWR"
controlled_by = ["LOWS_DEL"]

[[stations]]
id = "LOWW_DEL"
parent_id = "LOWW_GND"
controlled_by = ["LOWW_DEL"]

# minor aerodromes
[[stations]]
id = "LOAA_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOAA_TWR"]

[[stations]]
id = "LOAB_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAB_TWR"]

[[stations]]
id = "LOAD_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAD_TWR"]

[[stations]]
id = "LOAG_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAG_TWR"]

[[stations]]
id = "LOAN_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAN_TWR"]

[[stations]]
id = "LOAR_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAR_TWR"]

[[stations]]
id = "LOAS_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAS_TWR"]

[[stations]]
id = "LOAU_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAU_TWR"]

[[stations]]
id = "LOAV_TWR"
parent_id = "LOWW_I_APP"
controlled_by = ["LOAV_TWR"]

[[stations]]
id = "LOGF_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGF_TWR"]

[[stations]]
id = "LOGG_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGG_TWR"]

[[stations]]
id = "LOGI_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGI_TWR"]

[[stations]]
id = "LOGK_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGK_TWR"]

[[stations]]
id = "LOGL_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGL_TWR"]

[[stations]]
id = "LOGM_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGM_TWR"]

[[stations]]
id = "LOGO_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGO_TWR"]

[[stations]]
id = "LOGP_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGP_TWR"]

[[stations]]
id = "LOGT_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGT_TWR"]

[[stations]]
id = "LOGW_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOGW_TWR"]

[[stations]]
id = "LOIH_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOIH_TWR"]

[[stations]]
id = "LOIJ_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOIJ_TWR"]

[[stations]]
id = "LOIK_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOIK_TWR"]

[[stations]]
id = "LOIR_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOIR_TWR"]

[[stations]]
id = "LOKF_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKF_TWR"]

[[stations]]
id = "LOKG_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKG_TWR"]

[[stations]]
id = "LOKH_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKH_TWR"]

[[stations]]
id = "LOKL_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKL_TWR"]

[[stations]]
id = "LOKM_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKM_TWR"]

[[stations]]
id = "LOKN_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKN_TWR"]

[[stations]]
id = "LOKR_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKR_TWR"]

[[stations]]
id = "LOKW_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOKW_TWR"]

[[stations]]
id = "LOLC_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLC_TWR"]

[[stations]]
id = "LOLE_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLE_TWR"]

[[stations]]
id = "LOLF_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLF_TWR"]

[[stations]]
id = "LOLG_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLG_TWR"]

[[stations]]
id = "LOLH_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLH_TWR"]

[[stations]]
id = "LOLK_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLK_TWR"]

[[stations]]
id = "LOLM_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLM_TWR"]

[[stations]]
id = "LOLO_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLO_TWR"]

[[stations]]
id = "LOLS_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLS_TWR"]

[[stations]]
id = "LOLT_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLT_TWR"]

[[stations]]
id = "LOLU_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLU_TWR"]

[[stations]]
id = "LOLW_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOLW_TWR"]

[[stations]]
id = "LOSM_TWR"
parent_id = "LOVV_I_CTR"
controlled_by = ["LOSM_TWR"]
