[[stations]]
id = "EDXX-FIS"
controlled_by = ["EDXX_IDS_CTR"]

[[stations]]
id = "EDXX-FIS-GG"
controlled_by = ["EDXX_IDR_CTR"]
parent_id = "EDXX-FIS"

[[stations]]
id = "EDXX-FIS-MM"
controlled_by = ["EDXX_IDO_CTR"]
parent_id = "EDXX-FIS"

[[stations]]
id = "EDXX-FIS-WW"
controlled_by = ["EDXX_IDV_CTR"]
parent_id = "EDXX-FIS"

[[stations]]
id = "EDXX-FIS-IDL"
controlled_by = ["EDXX_IDL_CTR"]
parent_id = "EDXX-FIS-GG"

[[stations]]
id = "EDXX-FIS-IDB"
controlled_by = ["EDXX_IDB_CTR"]
parent_id = "EDXX-FIS-WW"

[[stations]]
id = "EDXX-FIS-IDM"
controlled_by = ["EDXX_IDM_CTR"]
parent_id = "EDXX-FIS-MM"

[[stations]]
id = "EDXX-FIS-IDC"
controlled_by = ["EDXX_IDC_CTR"]
parent_id = "EDXX-FIS-MM"

[[stations]]
id = "EDXX-FIS-IDF"
controlled_by = ["EDXX_IDF_CTR"]
parent_id = "EDXX-FIS-GG"

[[stations]]
id = "EDXX-FIS-IDH"
controlled_by = ["EDXX_IDH_CTR"]
parent_id = "EDXX-FIS-WW"

[[stations]]
id = "EDXX-FIS-IDL"
controlled_by = ["EDXX_IDL_CTR"]
parent_id = "EDXX-FIS-GG"

[[stations]]
id = "EDXX-FIS-IDL"
controlled_by = ["EDXX_IDL_CTR"]
parent_id = "EDXX-FIS-GG"
