name: CI â€¢ Dataset

on:
  push:
    branches:
      - main
    paths:
      - "dataset/**"
      - ".github/workflows/ci-dataset.yml"
  pull_request:
    branches:
      - main
    paths:
      - "dataset/**"
      - ".github/workflows/ci-dataset.yml"
  workflow_call:

permissions: {}

jobs:
  schema:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install check-jsonschema
        run: pipx install check-jsonschema

      - name: Validate positions
        run: |
          shopt -s nullglob
          files=(dataset/*/positions.json dataset/*/positions.toml)
          if [ ${#files[@]} -gt 0 ]; then
            check-jsonschema --schemafile docs/schemas/positions.schema.json "${files[@]}"
          fi

      - name: Validate stations
        run: |
          shopt -s nullglob
          files=(dataset/*/stations.json dataset/*/stations.toml)
          if [ ${#files[@]} -gt 0 ]; then
            check-jsonschema --schemafile docs/schemas/stations.schema.json "${files[@]}"
          fi

      - name: Validate profiles
        run: |
          shopt -s nullglob
          files=(dataset/*/profiles/*.json)
          if [ ${#files[@]} -gt 0 ]; then
            check-jsonschema --schemafile docs/schemas/profiles.schema.json "${files[@]}"
          fi

  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "linux-x86_64"
          workspaces: "tools -> target"

      - name: Validate dataset
        run: cargo run --quiet --release --locked --bin vacs-data --manifest-path tools/Cargo.toml -- --log-format github validate dataset/
